apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: demo
  namespace: demo
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values: 
          - demo
---
apiVersion: v1
kind: Namespace
metadata:
  name: ggithubcom-jhuss7-appheirdemo-ns
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  annotations:
    apps.open-cluster-management.io/reconcile-rate: medium
  name: ggithubcom-jhuss7-appheirdemo
  namespace: ggithubcom-jhuss7-appheirdemo-ns
spec:
  type: Git
  pathname: 'https://github.com/jhuss7/appheirdemo'
  insecureSkipVerify: true
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: inside
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: demo
  name: demo-subscription-1
  namespace: hello-mt
spec:
  channel: ggithubcom-jhuss7-appheirdemo-ns/ggithubcom-jhuss7-appheirdemo
  placement:
    placementRef:
      kind: PlacementRule
      name: demo-placement-1
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: demo
  name: demo-placement-1
  namespace: hello-mt
spec:
  clusterSelector:
    matchLabels:
      'local-cluster': 'true'
